[global]
showWarningOnDirectExecution = false

[logger]
level = "debug"

[client]
showErrorDetails = false

[runner]
magicEnabled = true
installTracer = true

[browser]
gatherUsageStats = false

[deprecation]
showfileUploaderEncoding = "True"
showPyplotGlobalUse = "False"

# [theme]
# primaryColor="#f30b45"
# secondaryBackgroundColor="#94a68e"
# backgroundColor="#e8e8e3"
# textColor="#000000"
# font = "sans serif"