ANTHROPIC_CLAUDE_API_KEY="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"
ANTHROPIC_CLAUDE_API_KEY_TEST="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"
ANTHROPIC_CLAUDE_API_KEY_TENANT_PROFILE="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"
ANTHROPIC_CLAUDE_API_KEY_PERSONNEL_PROFILE="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"
ANTHROPIC_CLAUDE_API_KEY_5="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"
ANTHROPIC_TEST_ONLY_API_KEY="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"
ANTHROPIC_SECOND_TEST_API_KEY="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"
ANTHROPIC_API_KEY_No_8="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"
ANTHROPIC_API_KEY_No_9="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"
ANTHROPIC_API_KEY_No_10="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"

ANTHROPIC_MASTER_API_KEY="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"

CLAUDE_AI_API_KEY="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"

GOOGLE_MAPS_GEOCODING_API_KEY="AIzaSyBg8e9nuFCzYsCpGdvqlUmd5E8vZ3vvygQ"
GOOGLE_SEARCH_API_KEY = "AIzaSyBzovNumfUuHSAELeObluCqAZVxITffNpo"
GOOGLE_SEARCH_ID = "c1fd5f7566d6a4248"

VOYAGEAI_API_KEY="pa-IVXTlNsMBOq2sAQPrTQKIylPw_KFm8dQdc4Mi5v0zPA"

SERPAPI="4bb867d9fc83884c6e4745296a87a24e8cefa93dcfe21e5f5c06341ad0b6015e"

OPENAI_API_KEY="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"

SERPER_API_KEY="0eed1249c824bbb13f9e360587a4bdb5e00d102a"